server {
    listen 80;
    server_name adminer.local;

    location / {
        # 'my_adminer' là tên container_name (hoặc tên service) của Adminer
        # '8080' là port nội bộ mà container Adminer đang chạy
        proxy_pass http://adminer:8080;

        # Truyền thông tin header thực của client tới Adminer
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
