services:
  redis_{{PROJECT_NAME}}:
    image: redis:alpine
    container_name: {{PROJECT_NAME}}_redis
    ports:
      - "6379:6379"
    networks:
      - global_network_docker

networks:
  global_network_docker:
    external: true
